export const objectInfo = {
      eingang: {
        title: "Eingangsbereich und Garderobe",
        images: ["assets/references/holzgang-fenster.jpg"],
        description: "Ankommenszone mit Garderobe, Elterninformationen und bewusst gestalteter Begrüßungssituation.",
        theory: [
          "Der bundesländerübergreifende BildungsRahmenPlan ist das primäre Grundlagendokument für elementarpädagogische Bildungseinrichtungen in Österreich. Eine neue Auflage ist für Ende 2026 angekündigt.",
          "Er beschreibt das Bild vom Kind, die professionelle Haltung des Fachpersonals, Prinzipien für Bildungsprozesse, Kompetenzen, die sechs Bildungsbereiche sowie Qualitätsentwicklung und Transitionen.",
          "Einzelbeschäftigung: ein Kind.",
          "Tandemtätigkeit: zwei Kinder oder ein Kind und eine elementarpädagogische Fachperson.",
          "Kleingruppe: 3 bis 6 Kinder. Teilgruppe: 7 bis 12 Kinder. Gesamtgruppe: 13 bis 23 Kinder beziehungsweise alle Kinder der Gruppe."
        ],
        documents: [
          { type: "PDF", title: "BildungsRahmenPlan Österreich", note: "Primäres Grundlagendokument für elementarpädagogische Bildungseinrichtungen", href: "assets/grundlagen/BildungsRahmenPlan_Oesterreich.pdf" },
          { type: "PDF", title: "Übersicht der Grundlagendokumente", note: "Poster zur gemeinsamen pädagogischen Orientierung und den Vertiefungsdokumenten", href: "assets/grundlagen/Grundlagendokumente_Uebersicht.pdf" },
          { type: "PDF", title: "Werte- und Orientierungsleitfaden", note: "Wertebildung, professionelle Reflexion und pädagogische Praxis", href: "assets/grundlagen/Werte_Orientierungsleitfaden.pdf" },
          { type: "PDF", title: "Modul für das letzte Jahr", note: "Vertiefung für das letzte Jahr in elementaren Bildungseinrichtungen", href: "assets/grundlagen/Modul_letztes_Kindergartenjahr.pdf" },
          { type: "PDF", title: "Leitfaden sprachliche Bildung und Förderung", note: "Sprachliche Bildung am Übergang in die Volksschule", href: "assets/grundlagen/Sprachliche_Bildung_Foerderung.pdf" },
          { type: "PDF", title: "Mindestausstattung im Kindergarten", note: "Verbindliche Ausstattungsgrundlage der Fachaufsicht Steiermark, Stand September 2019", href: "assets/grundlagen/Mindestausstattungen_Kindergarten.pdf" }
        ],
        areas: ["Emotionen und soziale Beziehungen", "Sprache und Kommunikation", "Ethik und Gesellschaft"],
        age: "2 bis 6 Jahre",
        material: "Garderobenhaken, Namenssymbole, Elternboard, Fotodokumentation, Grundlagendokumente, Tisch und zwei Sessel",
        prep: "gering",
        duration: "täglich 5 bis 15 Minuten",
        season: "ganzjährig",
        group: "Einzelkind, Kleingruppe, Eltern-Kind-Situation",
        goals: ["Übergänge sicher gestalten", "Beziehung und Vertrauen aufbauen", "Selbstständigkeit beim Ankommen fördern"],
        variations: ["Begrüßungsritual mit Symbolkarten", "Wochenfrage am Elternboard", "Kinder fotografieren ihre Lieblingsroutine"],
        tips: ["Blickkontakt und ruhige Sprache geben Sicherheit.", "Informationen für Eltern knapp, sichtbar und aktuell halten."],
        safety: ["Fluchtwege frei halten", "Haken und Ablagen auf Kinderhöhe sicher montieren"],
        documentation: ["Ankommensbeobachtungen notieren", "Übergänge im Portfolio sichtbar machen"],
        sources: ["Bundesländerübergreifender BildungsRahmenPlan Österreich", "Transitionen in der Elementarpädagogik"]
      },
      gruppenraum: {
        title: "Gruppenraum",
        images: ["assets/references/gruppenraum.jpg", "assets/references/holzbau-aussen.jpg"],
        description: "Offener Hauptbereich mit Bau-, Rollen-, Lese- und Kommunikationszonen.",
        minimum: ["Mindestens 50 didaktische Spiele, darunter Puzzle, Würfel- und Kartenspiele sowie Sinnes- und Montessori-Materialien.", "Lege-, Fädel- und Steckmaterial sowie zehn unterschiedliche Materialien zur Sinneswahrnehmung.", "PC oder Laptop mit Internetzugang und Digitalkamera pro Einrichtung; ein Tablet ist optional."],
        areas: ["Emotionen und soziale Beziehungen", "Sprache und Kommunikation", "Ästhetik und Gestaltung"],
        age: "3 bis 6 Jahre",
        material: "Modulare Regale, Teppiche, Bücher, Bauklötze, Rollenspielmaterialien",
        prep: "mittel",
        duration: "Freispiel und Impulsphasen",
        season: "ganzjährig",
        group: "Kleingruppe bis Gesamtgruppe",
        goals: ["Selbstbestimmtes Spiel ermöglichen", "Kooperation und Sprache im Alltag anregen", "Raum als dritten Pädagogen nutzen"],
        variations: ["Themeninseln wechseln", "Kinder an der Raumgestaltung beteiligen", "Materialtabletts für offene Impulse"],
        tips: ["Zonen visuell klar trennen, aber Wege offen lassen.", "Weniger Material, dafür gut ausgewählt und zugänglich."],
        safety: ["Regale kippsicher befestigen", "Laufwege zwischen Spielzonen freihalten"],
        documentation: ["Spielprozesse fotografisch dokumentieren", "Kinderzitate sammeln"],
        sources: ["Raumgestaltung in elementaren Bildungseinrichtungen", "Reggio-inspirierte Raumkonzepte"]
      },
      bauteppich: {
        title: "Bauteppich",
        description: "Konstruktionsbereich für mathematische, technische und soziale Lernprozesse.",
        minimum: ["Mindestens zwei Kleinbaustein-Bausysteme in einer Menge für drei unabhängig tätige Kinder.", "Großbausteine in unterschiedlichen geometrischen Formen für drei Kinder.", "Mindestens drei Arten Konstruktionsmaterial, Belebungsmaterial sowie Eisenbahnschienen, Lokomotiven und Waggons."],
        areas: ["Natur und Technik", "Emotionen und soziale Beziehungen", "Sprache und Kommunikation"],
        age: "3 bis 6 Jahre",
        material: "Holzbausteine, Magnetbausteine, Röhren, Figuren, Fotos von Bauwerken",
        prep: "gering bis mittel",
        duration: "20 bis 60 Minuten",
        season: "ganzjährig",
        group: "2 bis 8 Kinder",
        goals: ["Statik und Gleichgewicht erproben", "Planen, Vergleichen und Messen anbahnen", "Absprachen in der Gruppe üben"],
        variations: ["Brückenbau-Challenge", "Bauwerk nach Foto nachbauen", "Stadt für Fahrzeuge entwickeln"],
        tips: ["Offene Fragen stellen: Was macht euren Turm stabil?", "Bauten nicht sofort wegräumen, wenn Lernprozesse sichtbar sind."],
        safety: ["Hohe Bauten auf sichere Höhe begrenzen", "Kleinteile altersgerecht auswählen"],
        documentation: ["Bauphasen fotografieren", "Kinderpläne und Erklärungen neben dem Bauwerk sammeln"],
        sources: ["Frühe mathematische Bildung", "Technikbildung im Kindergarten"]
      },
      leseecke: {
        title: "Lesebereich und Bücherregal",
        images: ["assets/references/lesebereich-canopy.jpg", "assets/references/lesebereich-hell.jpg"],
        description: "Ruhiger Literacy-Bereich mit Bilderbüchern, Gesprächsanlässen und Rückzugsmöglichkeit.",
        minimum: ["Mindestens 50 Bücher: Bilder- und Wimmelbücher, Sachbücher, Märchen, fantastische Geschichten, mehrsprachige Bücher, Bücher über Religionen und Weltanschauungen sowie Liederbücher.", "Entspannendes Mobiliar wie Teppich, Couch oder Sitzkissen, Pölster und Decken.", "Bildkarten und Buchstaben sowie Hand- und Fingerpuppen als Sprachfördermaterialien."],
        areas: ["Sprache und Kommunikation", "Emotionen und soziale Beziehungen", "Ethik und Gesellschaft"],
        age: "2 bis 6 Jahre",
        material: "Bilderbücher, Sitzkissen, Erzählkarten, mehrsprachige Bücher, Kamishibai",
        prep: "gering",
        duration: "10 bis 30 Minuten",
        season: "ganzjährig",
        group: "Einzelbeschäftigung bis Kleingruppe",
        goals: ["Wortschatz erweitern", "Dialogisches Lesen anregen", "Empathie und Perspektivenübernahme fördern"],
        variations: ["Buch der Woche", "Bilderbuchkino", "Kinder erzählen mit Figuren weiter"],
        tips: ["Bücher frontal sichtbar präsentieren.", "Mehrsprachigkeit sichtbar und wertschätzend einbinden."],
        safety: ["Rückzug respektieren", "Bücher altersgerecht auswählen"],
        documentation: ["Lieblingsbücher der Kinder sammeln", "Sprachliche Beobachtungen festhalten"],
        sources: ["Literacy in der frühen Kindheit", "Dialogisches Lesen"]
      },
      schauplatzgestaltung: {
        title: "Schauplatzgestaltung",
        images: ["assets/schauplatz/schauplatz.jpeg"],
        description: "Eine Bilderbuchgeschichte wird mit Figuren, Naturmaterialien und einer gestalteten Miniaturlandschaft sichtbar, begreifbar und gemeinsam bespielbar gemacht.",
        theory: [
          "Die Methode verbindet Sprache, Handlung und Material. Kinder verfolgen das Geschehen im Raum und erhalten visuelle sowie haptische Zugänge zur Geschichte.",
          "Ausgangspunkt ist ein Bilderbuch mit klaren Handlungsorten. Der Schauplatz zeigt zentrale Orte und Figuren, verändert sich beim Erzählen und bleibt für das selbstständige Nachspielen zugänglich.",
          "Die elementarpädagogische Fachperson lädt zum Entdecken ein, bewegt Figuren passend zur Erzählung und öffnet den Verlauf für Ideen, Perspektiven und neue Erzählstränge der Kinder."
        ],
        documents: [
          { type: "DOCX", title: "Beispielplanung mit Erklärungen", note: "Ausführliches Planungskonzept mit Einstimmung, Hauptteil, Ausklang, Differenzierung und Reflexion", href: "assets/schauplatz/Beispielplanung_Schauplatzgestaltung.docx" },
          { type: "DOCX", title: "Handout Schauplatzgestaltung", note: "Definition, Bedeutung, methodisches Vorgehen und geförderte Kompetenzen", href: "assets/schauplatz/Handout_Schauplatzgestaltung.docx" },
          { type: "PDF", title: "Rezept für eine gelungene Schauplatzgestaltung", note: "Kompakter Praxisimpuls zur Vorbereitung und Umsetzung", href: "assets/schauplatz/Rezept_Schauplatzgestaltung.pdf" }
        ],
        areas: ["Sprache und Kommunikation", "Ästhetik und Gestaltung", "Emotionen und soziale Beziehungen"],
        age: "3 bis 6 Jahre",
        material: "Bilderbuch, Teppich, Figuren, Miniaturbäume, Sträucher, Fluss- und Landschaftselemente, Naturmaterialien und Tücher",
        prep: "mittel bis hoch",
        duration: "20 bis 45 Minuten; anschließend frei bespielbar",
        season: "ganzjährig und themenbezogen",
        group: "Kleingruppe bis Teilgruppe",
        goals: ["Geschichten verstehen und in eigenen Worten weitererzählen", "Perspektiven und Gefühle von Figuren nachvollziehen", "Szene gemeinsam gestalten und Handlungsverläufe aushandeln"],
        competencies: {
          self: ["Eigene Vorstellungen und Gefühle zur Geschichte ausdrücken.", "Eine passende Rolle oder Aufgabe selbstständig wählen und ausgestalten."],
          social: ["Ideen anderer aufgreifen, Rollen absprechen und gemeinsam erzählen.", "An den Gefühlen und Handlungen der Figuren sowie anderer Kinder Anteil nehmen."],
          subject: ["Figuren, Orte und zeitliche Abläufe einer Geschichte erkennen, benennen und ordnen.", "Materialien symbolisch einsetzen und sprachliche Zusammenhänge herstellen."],
          learningMethod: ["Erkennen, wie Bilderbuch, Erzählung und gestaltete Szene einander ergänzen.", "Bekannte Handlungsmuster auf neue Geschichten und Materialien übertragen."],
          meta: ["Das eigene Verständnis der Geschichte überprüfen und durch Nachfragen oder Nachspielen erweitern.", "Mit Unterstützung eine Aufgabe in der Zone der nächsten Entwicklung wählen."]
        },
        variations: ["Schauplatz gemeinsam aufbauen", "Figuren- oder Schattentheater", "Geschichte verändern oder weiterdenken", "Naturklänge und Musik integrieren"],
        tips: ["Die Szene zunächst abdecken und gemeinsam enthüllen.", "Nach dem Erzählen Zeit für selbstgesteuertes Nachspielen lassen."],
        safety: ["Kleinteile altersgerecht auswählen", "Laufwege um den Teppich freihalten"],
        documentation: ["Kinderzitate und neue Erzählideen festhalten", "Veränderungen des Schauplatzes fotografisch dokumentieren"],
        sources: ["Handout Schauplatzgestaltung in der Elementarpädagogik", "Beispielplanung Schauplatzgestaltung Bernhardt"]
      },
      rollenspiel: {
        title: "Rollenspielbereich",
        description: "Flexible Bühne für Familie, Praxis, Markt, Werkstatt und andere Alltagssituationen.",
        minimum: ["Verkleidungsmaterial und Utensilien für mindestens drei Kinder.", "Drei unterschiedliche Puppen mit passender Kleidung sowie Puppenbett oder Puppenwagen.", "Haushalts- und Küchenutensilien, Stofftiere und Spiegel; zusätzlich Ausstattung für mindestens zwei Themen der Kleinen Welt."],
        areas: ["Emotionen und soziale Beziehungen", "Ethik und Gesellschaft", "Sprache und Kommunikation"],
        age: "3 bis 6 Jahre",
        material: "Tücher, Verkleidung, Alltagsgegenstände, Puppen, Kassa, Küchenmodule",
        prep: "mittel",
        duration: "20 bis 60 Minuten",
        season: "ganzjährig",
        group: "2 bis 6 Kinder",
        goals: ["Rollen aushandeln", "Alltagserfahrungen verarbeiten", "Sprache in sozialen Situationen nutzen"],
        variations: ["Arztpraxis", "Restaurant", "Baustelle", "Familienwohnung", "Postamt"],
        tips: ["Material offen halten, damit Kinder eigene Themen entwickeln.", "Kulturelle Vielfalt im Material sichtbar machen."],
        safety: ["Schnüre und Kleinteile prüfen", "Verkleidung leicht zugänglich und hygienisch lagern"],
        documentation: ["Rollenthemen beobachten", "Gesprächssituationen als Lernfenster nutzen"],
        sources: ["Spielpädagogik", "Sozial-emotionale Entwicklung"]
      },
      atelier: {
        title: "Atelier",
        images: ["assets/references/atelier.jpg"],
        description: "Farbiger Werkraum für Malen, Zeichnen, Gestalten, Materialexperimente und ästhetische Forschung.",
        minimum: ["Ausreichend Werk-, Mal- und Zeichenmaterial für mindestens acht unabhängig tätige Kinder sowie Malschürzen oder Malshirts.", "Spritzgitter, fünf Farbroller, Schwämme, Stempel und Spachteln; drei Hämmer, zwei Handbohrer, zwei Sägen, drei Schraubenzieher und drei Schraubstöcke oder Schraubzwingen.", "Verschiedene Papiere, Klebstoffe, Stifte, Farben und Pinsel; zehn Kinderscheren, zwei Linkshänderscheren, zwei Therapeutenscheren und eine große Papierschere.", "Knet- und Modelliermassen, Stoff, Kork, Ton, Wolle, Moosgummi sowie Stopf-, Näh- und Webnadeln."],
        areas: ["Ästhetik und Gestaltung", "Natur und Technik", "Sprache und Kommunikation"],
        age: "2 bis 6 Jahre",
        material: "Papier, Karton, Naturmaterialien, Ton, Farben, Pinsel, Staffeleien, Malwand, offene Materialkästen",
        prep: "mittel",
        duration: "20 bis 45 Minuten",
        season: "ganzjährig",
        group: "Einzelkind bis Kleingruppe",
        goals: ["Materialeigenschaften erforschen", "Eigene Ausdrucksformen entwickeln", "Prozesse wichtiger nehmen als Produkte"],
        variations: ["Malen zu Musik", "Naturdruck", "Tonspuren", "Gemeinschaftscollage", "Malwand für großformatige Teamarbeiten"],
        tips: ["Materialien schön und übersichtlich in Kästen präsentieren.", "Kinder dürfen Materialien selbst holen und nach Farbfamilien zurücksortieren.", "Nicht sofort bewerten, sondern Prozesse sprachlich begleiten."],
        safety: ["Ungiftige Materialien verwenden", "Scheren und Kleber altersgerecht begleiten", "Malwand und Boden gut abwischbar halten"],
        documentation: ["Prozessfotos statt nur Endprodukte", "Kinderkommentare neben Werken ausstellen"],
        sources: ["Ästhetische Bildung", "Atelierarbeit in Kindergärten"]
      },
      staffelei: {
        title: "Staffelei",
        description: "Vertikale Malfläche für großräumige Bewegungen, Farberfahrungen und Bildgestaltung.",
        areas: ["Ästhetik und Gestaltung", "Bewegung und Gesundheit"],
        age: "3 bis 6 Jahre",
        material: "Staffelei, große Papierbögen, Temperafarben, Schwämme, breite Pinsel",
        prep: "mittel",
        duration: "15 bis 35 Minuten",
        season: "ganzjährig",
        group: "1 bis 3 Kinder",
        goals: ["Körperbewegung und Gestaltung verbinden", "Farbmischungen entdecken", "Ausdauer und Feinmotorik stärken"],
        variations: ["Nur mit zwei Farben malen", "Malen mit Naturpinseln", "Gemeinschaftsbild über mehrere Tage"],
        tips: ["Arbeitskleidung bereitstellen.", "Kinder selbst Material wählen lassen."],
        safety: ["Rutschfester Boden", "Farben hautverträglich und auswaschbar"],
        documentation: ["Entstehungsschritte fotografieren", "Kinder über ihre Bilder erzählen lassen"],
        sources: ["Bildnerisches Gestalten im Elementarbereich"]
      },
      malwand: {
        title: "Malwand im Atelier",
        images: ["assets/references/malwand.webp"],
        description: "Eine robuste Wandfläche für großformatiges Malen, Spuren, Teamarbeiten und prozessorientierte Gestaltung.",
        areas: ["Ästhetik und Gestaltung", "Sprache und Kommunikation", "Emotionen und soziale Beziehungen"],
        age: "3 bis 6 Jahre",
        material: "Abwischbare Wandfläche, Papierrollen, Magnetleisten, breite Pinsel, Schwämme, Schürzen",
        prep: "mittel",
        duration: "20 bis 50 Minuten",
        season: "ganzjährig",
        group: "1 bis 6 Kinder",
        goals: ["Körper- und Armbewegung in Gestaltung übersetzen", "Gemeinsame Bildprozesse aushandeln", "Farben, Spuren und Formen vergleichen"],
        variations: ["Gemeinschaftswand zum Projektthema", "Malen mit beiden Händen", "Spuren mit Naturwerkzeugen"],
        tips: ["Die Wand als Prozessfläche nutzen, nicht nur als Ausstellungsfläche.", "Kinder beschreiben lassen, was sich im Bild verändert."],
        safety: ["Abwaschbare, ungiftige Farbe verwenden", "Rutschhemmende Unterlage bei Nassmaterialien"],
        documentation: ["Zeitreihe der Wand fotografieren", "Kinderzitate direkt neben Prozessfotos hängen"],
        sources: ["Atelierarbeit", "Ästhetische Forschung im Elementarbereich"]
      },
      materialschrank: {
        title: "Materialkästen im Atelier",
        images: ["assets/references/materialregal.jpg"],
        description: "Offene, sortierte Kästen ermöglichen Kindern eigenständige Materialwahl und Verantwortung für Ordnung.",
        areas: ["Ästhetik und Gestaltung", "Ethik und Gesellschaft", "Natur und Technik"],
        age: "3 bis 6 Jahre",
        material: "Transparente Boxen, Holzregale, Farbsymbole, Naturmaterialien, Papier, Kleber, Werkzeuge",
        prep: "mittel",
        duration: "laufend im Alltag",
        season: "ganzjährig",
        group: "Einzelkind bis Kleingruppe",
        goals: ["Selbstständigkeit fördern", "Materialeigenschaften vergleichen", "Sorgsamen Umgang mit Ressourcen lernen"],
        variations: ["Material des Monats", "Sortieren nach Farbe, Form oder Herkunft", "Kinder kuratieren eine Materialauswahl"],
        tips: ["Kästen auf Kinderhöhe platzieren.", "Fotos oder Symbole helfen beim Zurückräumen."],
        safety: ["Scharfe Werkzeuge getrennt lagern", "Kleinteile altersgerecht anbieten"],
        documentation: ["Materialentscheidungen beobachten", "Werke mit Materialkarten ergänzen"],
        sources: ["Vorbereitete Umgebung", "Bildung für nachhaltige Entwicklung"]
      },
      bewegung: {
        title: "Bewegungsraum",
        description: "Raum für Psychomotorik, Koordination, Tanz und Bewegungslandschaften.",
        minimum: ["Die Anforderungen gelten pro Bewegungsraum, nicht pro Gruppe.", "Fünf variationsreich kombinierbare Materialien und Turngeräte, darunter Kasten, Leiter und leichte Großelemente wie ein Satz WESCO.", "Eine Sprossenwand, zwei Langbänke mit Einhängehaken, eine Weichbodenmatte und mindestens drei Turnmatten.", "25 Bälle in mindestens zwei Ausführungen mit Luftpumpe sowie je 25 Seile und Gymnastikreifen.", "Gummiseil, Schwungtuch, 25 Sand-, Bohnen- oder Reissäckchen sowie je zwei Rollbretter und Balancierscheiben oder -platten."],
        theory: [
          "Bewegungserziehung umfasst angeleitete, teilangeleitete und freie Bewegungsformen und knüpft an Beobachtungen, Interessen und psychomotorische Voraussetzungen der Kinder an.",
          "Die methodische Reihe führt von Voraussetzungen schaffen über Erfahrungen sammeln und Bewegungserfahrungen festigen bis zum selbstständigen Anwenden.",
          "Eine Bewegungslandschaft ist eine teilangeleitete Bewegungsaktivität: Der Aufbau wird vorbereitet, die Kinder wählen Wege, Dauer und individuelle Lösungen möglichst selbstständig.",
          "Eine Bewegungsbaustelle ist eine freie Bewegungsform, bei der Kinder Geräte kombinieren und umbauen; pädagogische Fachkräfte begleiten aufmerksam und prüfen Stabilität und Sicherheit.",
          "Grundtätigkeitsformen wie Gehen, Laufen, Springen, Klettern, Balancieren, Werfen, Fangen, Ziehen, Schieben, Rollen und Kriechen bilden zentrale Planungsbezüge."
        ],
        documents: [
          { type: "PPTX", title: "Grundlagen: Bewegungsformen im Kindergarten", note: "46 Folien zu angeleiteten, teilangeleiteten und freien Bewegungsformen", href: "assets/bewegung/Bewegungsformen_Grundlagen.pptx" },
          { type: "DOCX", title: "Bewegungslandschaft Froschkönig", note: "Teilangeleitete Bewegungsaktivität für Kinder von 4 bis 6 Jahren", href: "assets/bewegung/Bewegungslandschaft_Froschkoenig.docx" },
          { type: "DOCX", title: "Bewegungsbaustelle unter drei Jahren", note: "Grundlagen, Begleitung und Sicherheitsaspekte", href: "assets/bewegung/Bewegungsbaustelle_unter_Drei.docx" },
          { type: "DOCX", title: "Handout Bewegungsformen", note: "Fachliche Übersicht und methodische Modelle", href: "assets/bewegung/Handout_Bewegungsformen.docx" },
          { type: "DOCX", title: "Vorbereitung Balancieren", note: "Angeleitete Bewegungseinheit nach der methodischen Reihe", href: "assets/bewegung/Vorbereitung_Balancieren.docx" }
        ],
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen"],
        age: "2 bis 6 Jahre",
        material: "Matten, Kästen, Balancierbalken, Tücher, Reifen, Bälle",
        prep: "mittel bis hoch",
        duration: "20 bis 50 Minuten",
        season: "ganzjährig",
        group: "Kleingruppe bis Halbgruppe",
        goals: ["Körperwahrnehmung stärken", "Gleichgewicht und Koordination fördern", "Mut und Selbstwirksamkeit erleben"],
        variations: ["Dschungelparcours", "Tanz mit Tüchern", "Partnerübungen", "Ruheinsel nach Bewegung"],
        tips: ["Aufbau vorab auf Sicherheitsabstände prüfen.", "Bewegungsaufgaben offen formulieren."],
        safety: ["Matten an Sprungstellen", "Schmuck ablegen", "klare Stoppsignale vereinbaren"],
        documentation: ["Bewegungsfortschritte beobachten", "Kinder über schwierige und leichte Stationen reflektieren lassen"],
        sources: ["Präsentation: Bewegungsformen im Kindergarten", "Renate Zimmer: Handbuch der Bewegungserziehung", "Konzept Bewegungsbaustelle nach Klaus Miedzinski", "Psychomotorik", "Bewegungserziehung im Kindergarten"]
      },
      bewegungsausstattung: {
        title: "Ausstattung im Bewegungsraum",
        description: "Offen zugängliche Groß- und Kleingeräte unterstützen vielfältige, sichere und veränderbare Bewegungserfahrungen.",
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen", "Natur und Technik"],
        age: "2 bis 6 Jahre",
        material: "Sprossenwand, Sportkästen, dicke und dünne Matten, WESCO-Schaumstoffbauteile, Turnsäckchen und Bewegungsbekleidung",
        prep: "abhängig vom Aufbau",
        duration: "10 bis 50 Minuten",
        season: "ganzjährig",
        group: "Einzelkind bis Halbgruppe",
        goals: ["Kraft, Koordination und Gleichgewicht erproben", "Materialeigenschaften und Risiken einschätzen", "Selbstständigkeit beim Vorbereiten stärken"],
        variations: ["Kletterweg an der Sprossenwand", "Kasten-Matten-Kombination", "WESCO-Bewegungsbaustelle", "Umziehritual mit Turnsäckchen"],
        tips: ["Geräte übersichtlich lagern und Laufwege freihalten.", "Aufbauten gemeinsam mit Kindern prüfen.", "Dicke Matten an Fallstellen, dünne Matten zum Bodenturnen verwenden."],
        safety: ["Sprossenwand und Kästen fest verankern", "Matten lückenlos anlegen", "WESCO-Teile auf festen Stand prüfen", "Trinkflasche außerhalb der Bewegungsfläche abstellen"],
        documentation: ["Materialwahl und Lösungswege beobachten", "Aufbauvarianten fotografisch festhalten", "Kinder zu Sicherheit und Schwierigkeit befragen"],
        sources: ["Grundlagendokumente Bewegungserziehung", "Sicherheitsorientierte Geräteerziehung"]
      },
      forscherraum: {
        title: "Forscherraum",
        images: ["assets/mint/forscherkreis.png", "assets/mint/kinder-forschen.jpg"],
        description: "Lernwerkstatt für Mathematik, Informatik, Naturwissenschaften und Technik. Kinder forschen selbsttätig, ko-konstruktiv und entlang des Forschungskreises.",
        minimum: ["Ausreichend Forschungsmaterial für mindestens zehn unabhängig tätige Kinder.", "Drei Lupen, fünf Lupenbecher und ein Mikroskop sowie Sammel- und Alltagsgegenstände.", "Uhren, Globus oder Weltkarte, optische Spiele, Messgefäße, Waage mit Gewichten und Magnete.", "Mehrere Trödel- und Geduldspiele sowie wertlose Materialien zum Untersuchen und Konstruieren."],
        theory: [
          "MINT umfasst Mathematik, Informatik, Naturwissenschaften und Technik. Frühe MINT-Bildung ist aktiv, selbsttätig, interessenorientiert, ganzheitlich, emotional beteiligt und mit allen Sinnen verbunden.",
          "Nachhaltiges Lernen knüpft an Interessen, Erfahrungen und Lebenswelt der Kinder an. Selbsttätigkeit, Alltagsbezug, soziale Interaktion und bewusste Reflexion unterstützen langfristig wirksame Lernprozesse.",
          "Ko-Konstruktion versteht Bildung als gemeinsamen Prozess: Wissen entsteht im Dialog zwischen Kindern sowie zwischen Kindern und elementarpädagogischen Fachpersonen.",
          "Der Forschungskreis führt vom Fragenstellen über Vorwissen und Hypothesen, Probieren und Experimentieren, Beobachten und Beschreiben sowie Dokumentieren zur gemeinsamen Reflexion.",
          "Die Lernbegleitung hört zu, fragt nach und gibt Freiheit, Raum und Zeit. Wie-Fragen aktivieren kindliches Denken häufiger als vorschnelle Erklärungen oder komplexe Warum-Fragen.",
          "Metakognition bedeutet Denken über das eigene Denken und Lernen. Kinder beschreiben ihre Lernwege, prüfen Vermutungen und erkennen mögliche nächste Entwicklungsschritte.",
          "Frühe positive MINT-Erfahrungen stärken Selbstkonzept, Motivation und Chancengerechtigkeit und können stereotypen Bildungsentscheidungen entgegenwirken."
        ],
        documents: [
          { type: "DOCX", title: "Handout: Didaktik früher MINT-Bildung", note: "Nachhaltiges Lernen, Ko-Konstruktion, Metakognition, Forschungskreis und pädagogische Haltung", href: "assets/mint/Handout_Didaktik_MINT.docx" },
          { type: "DOCX", title: "Handout: Bedeutung früher MINT-Bildung", note: "Zukunftskompetenzen, Chancengerechtigkeit, Selbstkonzept, Motivation und Gender-Gap", href: "assets/mint/MINT_Bedeutung_frueher_MINT_Bildung.docx" },
          { type: "PPTX", title: "Grundlagen: MINT-Bildung", note: "Theoretische Einführung in MINT, Ko-Konstruktion, Metakognition, Forschungskreis und Lernbegleitung", href: "assets/mint/MINT_Bildung_Bernhardt_Kolleg.pptx" }
        ],
        areas: ["Natur und Technik", "Sprache und Kommunikation"],
        age: "4 bis 6 Jahre",
        material: "Lupen, Waagen, Magnete, Messbecher, Naturmaterialien, Lichttisch",
        prep: "mittel",
        duration: "15 bis 40 Minuten",
        season: "ganzjährig",
        group: "2 bis 6 Kinder",
        goals: ["Fragen entwickeln", "Vermutungen überprüfen", "Beobachtungen sprachlich ausdrücken"],
        competencies: {
          self: ["Eigene Neugier, Interessen und Vorerfahrungen wahrnehmen und selbstbewusst in Forschungsprozesse einbringen.", "Unsicherheit und unerwartete Ergebnisse als Teil des Forschens aushalten."],
          social: ["Vermutungen, Beobachtungen und Erklärungen im Dialog austauschen und Wissen ko-konstruktiv weiterentwickeln.", "Materialien teilen, anderen zuhören und gemeinsame Untersuchungsschritte abstimmen."],
          subject: ["Mathematische, informatische, naturwissenschaftliche und technische Phänomene beobachten, vergleichen, ordnen, messen und beschreiben.", "Zusammenhänge durch eigenes Experimentieren prüfen und fachbezogene Begriffe situationsangemessen verwenden."],
          learningMethod: ["Den Forschungskreis nutzen: Fragen stellen, Vorwissen aktivieren, Hypothesen bilden, experimentieren, beobachten, dokumentieren und Ergebnisse reflektieren.", "Erkenntnisse auf neue Materialien, Phänomene und Alltagssituationen übertragen."],
          meta: ["Das eigene Denken und Lernen beschreiben, Vermutungen mit Ergebnissen vergleichen und Lernstrategien bewusst verändern.", "Mit angemessener Lernbegleitung den nächsten möglichen Entwicklungsschritt erkennen und erproben."]
        },
        variations: ["Schwimmen und Sinken", "Magnetwerkstatt", "Samen beobachten", "Licht und Schatten"],
        tips: ["Nicht vorschnell erklären, sondern Denkwege sichtbar machen.", "Forscherfragen der Kinder sammeln."],
        safety: ["Keine verschluckbaren Kleinteile für jüngere Kinder", "Wasser und Strom strikt trennen"],
        documentation: ["Forscherprotokoll mit Zeichnungen", "Vorher-Nachher-Fotos"],
        sources: ["Handout Didaktik MINT", "Handout Bedeutung früher MINT-Bildung", "Präsentation MINT-Bildung Bernhardt Kolleg", "Stiftung Haus der kleinen Forscher (2012)", "Fthenakis (2009)", "OECD (2020)", "Entdeckendes Lernen"]
      },
      lerntabletts: {
        title: "Mathematische Lerntabletts",
        images: ["assets/mint/lerntablett-formen.jpeg", "assets/mint/lerntablett-mengen-vergleichen.jpeg", "assets/mint/lerntablett-zahlen.jpeg"],
        description: "Übersichtliche Tabletts laden zum Sortieren, Zählen, Vergleichen, Messen und Legen mit Natur- und Alltagsmaterialien ein.",
        areas: ["Natur und Technik", "Ästhetik und Gestaltung", "Sprache und Kommunikation"], age: "3 bis 6 Jahre",
        material: "Holztabletts, Ziffern, Würfel, Naturmaterialien, geometrische Formen, Messwerkzeuge und Aufgabenkarten", prep: "gering bis mittel", duration: "10 bis 25 Minuten", season: "ganzjährig", group: "Einzelbeschäftigung oder Tandemtätigkeit",
        goals: ["Mengen erfassen und vergleichen", "Formen und Muster untersuchen", "Mathematische Beobachtungen versprachlichen"],
        variations: ["Zahlen und Mengen zuordnen", "Formen mit Steinen nachlegen", "Gewicht und Länge vergleichen"],
        tips: ["Je Tablett eine klar erkennbare Aufgabe anbieten.", "Mehrere Lösungswege offenhalten."], safety: ["Kleinteile altersangemessen einsetzen", "Naturmaterialien prüfen"], documentation: ["Lösungsstrategien beobachten", "Kinder ihre Regel erklären lassen"], sources: ["Frühe mathematische Bildung"]
      },
      waschbecken: {
        title: "Waschbecken auf Kinderhöhe", description: "Drei gut erreichbare Waschplätze unterstützen selbstständige Hygiene und bewusste Wassernutzung.",
        areas: ["Bewegung und Gesundheit", "Natur und Technik"], age: "2 bis 6 Jahre", material: "Kindgerechte Waschbecken, Armaturen, Seife und Handtücher", prep: "laufende Hygiene", duration: "individuell", season: "ganzjährig", group: "Einzelbeschäftigung bis Kleingruppe",
        goals: ["Hände selbstständig waschen", "Wasser bewusst dosieren", "Hygieneroutinen verstehen"], variations: ["Bildfolge zum Händewaschen"], tips: ["Alles sichtbar und erreichbar anbieten."], safety: ["Rutschfesten Boden und Temperaturbegrenzung sicherstellen"], documentation: ["Selbstständigkeit beobachten"], sources: ["Gesundheitsbildung"]
      },
      kindertoilette: {
        title: "Kindgerechte Toilettenkabinen", description: "Vier geschützte Kabinen verbinden Privatsphäre, gute Erreichbarkeit und selbstständige Körperpflege.",
        areas: ["Bewegung und Gesundheit", "Ethik und Gesellschaft", "Emotionen und soziale Beziehungen"], age: "2 bis 6 Jahre", material: "Vier Toiletten auf Kinderhöhe, Kabinentüren und leicht erreichbare Spülung", prep: "laufende Reinigung", duration: "individuell", season: "ganzjährig", group: "Einzelbeschäftigung",
        goals: ["Körpersignale wahrnehmen", "Intimsphäre achten", "Toilettenroutine selbstständig bewältigen"], variations: ["Piktogramme für Handlungsschritte"], tips: ["Hilfe ankündigen und bedarfsgerecht geben."], safety: ["Notöffnung ermöglichen", "Quetschstellen vermeiden"], documentation: ["Entwicklung sensibel dokumentieren"], sources: ["Kinderrechte und beziehungsvolle Pflege"]
      },
      dusche: {
        title: "Kindgerechte Dusche", description: "Eine bodennahe Dusche ermöglicht Reinigung nach Wasser-, Sand- und Matschaktivitäten.",
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen"], age: "2 bis 6 Jahre", material: "Bodengleiche Dusche, Handbrause, Rutschschutz und Sichtschutz", prep: "bei Bedarf", duration: "individuell", season: "ganzjährig", group: "Einzelbeschäftigung mit Fachperson",
        goals: ["Körperpflege sicher erleben", "Bedürfnisse und Grenzen ausdrücken"], variations: ["Füße nach dem Garten reinigen"], tips: ["Ablauf und Berührungen ankündigen."], safety: ["Rutschschutz, Temperaturbegrenzung und Aufsicht"], documentation: ["Keine Bilddokumentation in Pflegesituationen"], sources: ["Beziehungsvolle Pflege"]
      },
      trockenbereich: {
        title: "Trockenbereich für Kleidung", description: "Bank, Haken und Trockenstange schaffen Platz für nasse Gartenkleidung und Wechselwäsche.",
        areas: ["Bewegung und Gesundheit", "Ethik und Gesellschaft"], age: "2 bis 6 Jahre", material: "Sitzbank, Haken, Trockenstange und Wechselkleidung", prep: "gering", duration: "5 bis 15 Minuten", season: "ganzjährig", group: "Einzelbeschäftigung bis Kleingruppe",
        goals: ["Kleidung selbstständig ordnen", "Verantwortung für eigene Dinge übernehmen"], variations: ["Bildsymbole für Kleidungsstücke"], tips: ["Plätze eindeutig kennzeichnen."], safety: ["Abgerundete Haken", "Nasse Wege trocknen"], documentation: ["Selbstständigkeit beobachten"], sources: ["Alltagskompetenzen"]
      },
      musik: {
        title: "Musikbereich",
        images: ["assets/musik/rhythmikeinheit.jpeg"],
        description: "Klangraum für Rhythmik, Singen, Instrumente, Bewegung und Hörwahrnehmung.",
        minimum: ["Eine Gitarre und 15 ORFF-Instrumente, darunter Rahmen-, Schellen- und Holzblocktrommel, Becken, Triangel und Klangstäbe mit Schlegeln.", "15 Paar Klanghölzer sowie 15 verschiedene Rasseln und Schellenbäume oder -bänder.", "25 Chiffon- oder Tülltücher sowie CD-Player und verschiedene CDs."],
        theory: [
          "Musikalische Bildung verbindet Singen, Sprache, Bewegung, Wahrnehmung, Exploration und symbolisches Festhalten von Klängen.",
          "Pädagogische Fachkräfte bereiten Raum und Material vor, beobachten die Kinder und unterstützen zurückhaltend oder als Spielpartner:innen.",
          "Zentrale musikalische Parameter sind Zeitverlauf und Rhythmus, Tonhöhe, Dynamik und Klangfarbe.",
          "Eine Liederarbeitung führt von Vorüberlegungen und Warm-up über Motivation und abschnittsweises Erarbeiten zur Vertiefung und zum ruhigen Ausklang.",
          "Bewegung, Mimik, Gestik, Bodypercussion und Anschauungsmaterial erleichtern Textverständnis, Wortschatzarbeit und gemeinsames Erinnern.",
          "Instrumente brauchen eine freie Experimentierphase; anschließend können ORFF-Instrumente gezielt für Rhythmus, Bordun oder wiederkehrende Liedteile eingesetzt werden."
        ],
        documents: [
          { type: "DOCX", title: "Vorbereitung: Kastanienlied", note: "Ausgearbeitete Liederarbeitung zum Themenschwerpunkt Herbst", href: "assets/musik/VB_Kastanienlied.docx" },
          { type: "DOCX", title: "Vorbereitung: Hallo du, sagt die Kuh", note: "Ausgearbeitete Liederarbeitung zum Themenschwerpunkt Bauernhof", href: "assets/musik/VB_Kuhlied.docx" },
          { type: "DOCX", title: "Leerformular Liederarbeitung", note: "Planungsvorlage für eine eigene Liedeinführung", href: "assets/musik/VB_Leerformular_Liederarbeitung.docx" },
          { type: "PPTX", title: "Theorie: Singen und Musizieren mit Kindern", note: "55 Folien zu Didaktik, Liederarbeitung und ORFF-Instrumenten", href: "assets/musik/Theorie_Singen_Musizieren.pptx" },
          { type: "PDF", title: "Begleitheft Musik", note: "Musik, Interaktionsqualität und sprachliche Begleitung", href: "assets/musik/Begleitheft_Musik.pdf" }
        ],
        areas: ["Ästhetik und Gestaltung", "Sprache und Kommunikation", "Emotionen und soziale Beziehungen"],
        age: "2 bis 6 Jahre",
        material: "Orff-Instrumente, Klanghölzer, Trommeln, Tücher, Liedkarten",
        prep: "gering bis mittel",
        duration: "10 bis 30 Minuten",
        season: "ganzjährig",
        group: "Kleingruppe bis Gesamtgruppe",
        goals: ["Rhythmus erleben", "Hören und Nachahmen üben", "Gemeinschaft durch gemeinsames Musizieren stärken"],
        variations: ["Klanggeschichte", "Instrumente raten", "Laut-leise-Spiele", "Bewegungslied"],
        tips: ["Instrumente dosiert anbieten.", "Stille als Teil der Musik bewusst machen."],
        safety: ["Lautstärke begrenzen", "Instrumente pfleglich und sicher lagern"],
        documentation: ["Liederrepertoire dokumentieren", "Kinderkompositionen aufnehmen"],
        sources: ["Präsentation: Singen und Musizieren mit Kindern, SJ 2023/24", "Bachner et al. (2021): Musik. Gute Interaktionsqualität sichern und sprachlich begleiten", "Musikalische Frühförderung", "Rhythmik in der Elementarpädagogik"]
      },
      rhythmik: {
        title: "Rhythmikeinheit im Musikbereich",
        images: ["assets/musik/rhythmikeinheit.jpeg"],
        description: "Eine vorbereitete Kreismitte verbindet Instrumente, Tücher, Bewegung, Wahrnehmung und gemeinsames musikalisches Gestalten.",
        areas: ["Ästhetik und Gestaltung", "Bewegung und Gesundheit", "Emotionen und soziale Beziehungen"], age: "3 bis 6 Jahre",
        material: "ORFF-Instrumente, gestaltete Kreismitte, Chiffontücher, Sitzkissen und Naturmaterialien", prep: "mittel", duration: "20 bis 35 Minuten", season: "ganzjährig", group: "Kleingruppe bis Teilgruppe",
        goals: ["Musik und Bewegung verbinden", "Rhythmische Muster gestalten", "Gemeinsam beginnen, pausieren und ausklingen"],
        variations: ["Bewegung mit Tüchern", "Instrumentenwechsel", "Klang und Stille"], tips: ["Instrumente zuerst frei erkunden lassen."], safety: ["Bewegungsabstand schaffen", "Lautstärke regulieren"], documentation: ["Rhythmische Ideen der Kinder notieren"], sources: ["Rhythmik in der Elementarpädagogik"]
      },
      gitarre: {
        title: "Gitarre",
        description: "Saiteninstrument für Liedbegleitung, Klangexperimente und das Erleben von Rhythmus, Tonhöhe und Resonanz.",
        areas: ["Ästhetik und Gestaltung", "Sprache und Kommunikation", "Emotionen und soziale Beziehungen"],
        age: "3 bis 6 Jahre",
        material: "Gitarre, Plektrum, Liedkarten und gegebenenfalls Kapodaster",
        prep: "gering",
        duration: "5 bis 25 Minuten",
        season: "ganzjährig",
        group: "Tandemtätigkeit bis Gesamtgruppe",
        goals: ["Saitenschwingungen wahrnehmen", "Gesang rhythmisch begleiten", "Aufeinander hören und gemeinsam einsetzen"],
        variations: ["Saitenklänge vergleichen", "Liedbegleitung", "Klangrätsel", "Rhythmische Echo-Spiele"],
        tips: ["Das Instrument zunächst aus der Nähe betrachten lassen.", "Lautstärke und Anschlag gemeinsam erproben."],
        safety: ["Instrument standsicher aufbewahren", "Saiten und Stimmmechaniken regelmäßig kontrollieren"],
        documentation: ["Musikalische Reaktionen und Liedwünsche notieren", "Rhythmische Fortschritte beobachten"],
        sources: ["Musikalische Bildung im Elementarbereich", "Liedbegleitung mit der Gitarre"]
      },
      klanggeschichte: {
        title: "Bildungsaktivität: Klanggeschichte",
        description: "Eine erzählte Geschichte wird mit Tönen, Klängen, Geräuschen, Stimme, Bewegung und ausgewählten Instrumenten gemeinsam gestaltet.",
        theory: [
          "Zuerst die Geschichte mit Bildern oder Gegenständen erzählen und gemeinsam über ihren Inhalt sprechen.",
          "Instrumente vorstellen und ausreichend Zeit zum freien Erproben von Spielweisen, Tempo, Lautstärke und Klangfarbe geben.",
          "Signalwörter, Bildkarten und klare Handzeichen unterstützen Einsatz, Pause und Instrumentenwechsel.",
          "Jüngere Kinder beginnen mit einem Instrument und kurzen Wiederholungen; ältere Kinder übernehmen mehrere Klangrollen oder die Leitung.",
          "Zum Abschluss Instrumente gemeinsam zurücklegen, Klänge verklingen lassen und den Geschichtenverlauf reflektieren."
        ],
        documents: [
          { type: "DOCX", title: "Klanggeschichten erarbeiten", note: "Altersgerechter Aufbau von der Krippe bis zum Kindergarten", href: "assets/klanggeschichten/Klanggeschichten_erarbeiten.docx" },
          { type: "DOCX", title: "Grundlagen Klanggeschichten", note: "Definition, Explorationsphase und differenzierte Umsetzungshinweise", href: "assets/klanggeschichten/Klanggeschichten_Grundlagen.docx" },
          { type: "DOCX", title: "Beispielplanung: Fleißige Bienen", note: "Ausgearbeitete Klanggeschichte für Kinder von 5 bis 6 Jahren", href: "assets/klanggeschichten/Planung_Klanggeschichte_Bienen.docx" },
          { type: "PDF", title: "Fingerspiel: Bienchen, Bienchen, summ", note: "Ergänzender Impuls zur Bienenklanggeschichte", href: "assets/klanggeschichten/Fingerspiel_Bienchen.pdf" }
        ],
        areas: ["Ästhetik und Gestaltung", "Sprache und Kommunikation", "Emotionen und soziale Beziehungen"],
        age: "ab 1 Jahr, differenziert bis 6 Jahre",
        material: "Bildkarten, Gegenstände, ORFF-Instrumente, Stimme, Körper und Alltagsmaterialien",
        prep: "mittel",
        duration: "10 bis 30 Minuten",
        season: "ganzjährig",
        group: "Kleingruppe",
        goals: ["Klänge bewusst wahrnehmen und vergleichen", "Einsatz, Pause und gemeinsames Tempo koordinieren", "Geschichten sprachlich und musikalisch ausdrücken"],
        variations: ["Ein Instrument für alle", "Mehrere Klangrollen", "Geschichte ohne Sprache", "Kind übernimmt die Dirigierrolle", "Eigene Klanggeschichte erfinden"],
        tips: ["Explorationsphase nicht abkürzen.", "Gleiche Instrumente nebeneinander platzieren.", "Stille als bewusstes Gestaltungsmittel einplanen."],
        safety: ["Lautstärke und Abstände vereinbaren", "Instrumente altersgerecht auswählen", "Achtsamen Umgang vormachen"],
        documentation: ["Instrumentenzuordnungen fotografieren", "Kinderideen und neue Klangvarianten notieren", "Geschichtenfolge mit Bildkarten sichern"],
        sources: ["Scheer und Gulden: Klanggeschichten in Krippe und Kindergarten", "Kunkel (2015)", "Lambrecht (2019)"]
      },
      orffregal: {
        title: "Offenes ORFF-Instrumentenregal",
        description: "Ein übersichtlicher, frei zugänglicher Kasten ordnet Instrumente nach Klangfamilie und macht selbstständige Auswahl möglich.",
        images: ["assets/klanggeschichten/referenz-stabspiel.png", "assets/klanggeschichten/referenz-ratsche.png"],
        documents: [
          { type: "DOCX", title: "ORFF-Instrumente im Überblick", note: "Instrumentennamen, Abbildungen und passende Spielwerkzeuge", href: "assets/klanggeschichten/ORFF_Instrumente.docx" }
        ],
        areas: ["Ästhetik und Gestaltung", "Natur und Technik", "Emotionen und soziale Beziehungen"],
        age: "2 bis 6 Jahre",
        material: "Handtrommel, Stabspiel, Klanghölzer, Triangel, Rasseln, Guiro und Schlägel",
        prep: "gering",
        duration: "freie Exploration oder angeleitete Sequenz",
        season: "ganzjährig",
        group: "Einzelkind bis Kleingruppe",
        goals: ["Instrumente benennen", "Spielweisen und Klangfarben unterscheiden", "Material selbstständig auswählen und zurückordnen"],
        variations: ["Sortieren nach Material", "Klang-Memory", "Instrumentenfamilien vergleichen", "Dirigierspiel"],
        tips: ["Instrumente sichtbar und auf Kinderhöhe anbieten.", "Schlägel direkt beim passenden Instrument lagern."],
        safety: ["Regal kippsicher befestigen", "Beschädigte Instrumente aussortieren", "Schlägel nicht zweckentfremden"],
        documentation: ["Lieblingsinstrumente beobachten", "Klangbeschreibungen der Kinder sammeln"],
        sources: ["ORFF Instrumente - Auflistung", "Elementare Musikpädagogik"]
      },
      ruheraum: {
        title: "Ruheraum",
        description: "Rückzugsort für Entspannung, Bilderbücher, Atemübungen und leise Gespräche.",
        minimum: ["Mobiliar, das zum Entspannen und Ausruhen einlädt, beispielsweise Teppich, Couch oder Sitzkissen, Pölster und Decken.", "Der Rückzug muss ungestörtes Spiel allein oder gemeinsam mit einem oder zwei anderen Kindern ermöglichen."],
        areas: ["Emotionen und soziale Beziehungen", "Bewegung und Gesundheit"],
        age: "2 bis 6 Jahre",
        material: "Matten, Kissen, Decken, gedämpftes Licht, Bilderbücher, Klangschale",
        prep: "gering",
        duration: "individuell, 5 bis 30 Minuten",
        season: "ganzjährig",
        group: "Einzelkind bis Kleingruppe",
        goals: ["Selbstregulation unterstützen", "Ruhebedürfnisse wahrnehmen", "Körper und Gefühle differenzieren"],
        variations: ["Atemgeschichte", "Fantasiereise", "Bilderbuch im Flüsterton", "Gefühlskarten"],
        tips: ["Ruhe nicht erzwingen, sondern einladend anbieten.", "Klare Regeln für Lautstärke und Rückzug vereinbaren."],
        safety: ["Aufsicht und Sichtbarkeit sicherstellen", "Kissen und Decken hygienisch pflegen"],
        documentation: ["Regulationsstrategien einzelner Kinder beobachten", "Rückzugsbedürfnisse im Team reflektieren"],
        sources: ["Gesundheitsbildung", "Emotionsregulation in der frühen Kindheit"]
      },
      garten: {
        title: "Garten",
        description: "Außenraum für Naturerfahrungen, Bewegung, Wasser, Sinneserfahrungen und jahreszeitliche Projekte.",
        minimum: ["Sandspielfläche von mindestens 10 m² und 0,50 m Tiefe; für jede weitere Gruppe zusätzlich 5 m². Mindestens zwei Drittel müssen beschattet sein.", "Fünf große und fünf kleine Sandschaufeln, drei Rechen, Besen, drei Siebtruhen, fünf Eimer, Behälter, Trichter, Schöpfer, Pipetten und drei Gießkannen sowie Kipper, Bagger und Lastwagen.", "Schaukelmöglichkeiten für zwei Kinder gleichzeitig, darunter mindestens eine Brettschaukel.", "Klettern, Balancieren und Hängen für mindestens fünf Kinder gleichzeitig sowie fünf Fahrzeuge für drinnen oder draußen."],
        areas: ["Natur und Technik", "Bewegung und Gesundheit", "Emotionen und soziale Beziehungen"],
        age: "2 bis 6 Jahre",
        material: "Wiese, Sand, Wasser, Pflanzen, Fahrzeuge, Werkzeug, Naturmaterialien",
        prep: "mittel",
        duration: "20 bis 90 Minuten",
        season: "Frühling, Sommer, Herbst, Winter",
        group: "Kleingruppe bis Gesamtgruppe",
        goals: ["Natur mit allen Sinnen erleben", "Grobmotorik fördern", "Verantwortung für Umwelt entwickeln"],
        variations: ["Barfußpfad", "Wassertransport", "Gartenbeobachtung", "Blätterwerkstatt"],
        tips: ["Draußen nicht nur Pause denken, sondern Bildungsraum.", "Naturfragen der Kinder als Projektstart nutzen."],
        safety: ["Sonnenschutz, Wetterkleidung, Giftpflanzenkontrolle", "Fahrwege und Laufwege trennen"],
        documentation: ["Jahreszeitenportfolio", "Naturfund-Tisch mit Kinderfragen"],
        sources: ["Naturpädagogik", "Bildung für nachhaltige Entwicklung"]
      },
      gartentor: {
        title: "Gesichertes Gartentor",
        description: "Zweiflügeliger Zugang am Ende des Gartenwegs. Der elektronische Türöffner ist außen und deutlich außerhalb der Reichweite von Kindern montiert.",
        areas: ["Ethik und Gesellschaft", "Bewegung und Gesundheit"],
        age: "gesamte Einrichtung",
        material: "Durchgehender Zaun, selbstschließendes Gartentor, erhöhter elektronischer Türöffner und Sichtkontrolle",
        prep: "laufende Funktionskontrolle",
        duration: "bei jedem Betreten und Verlassen",
        season: "ganzjährig",
        group: "Einzelbeschäftigung bis Gesamtgruppe",
        goals: ["Sichere Übergänge gewährleisten", "Verantwortungsbewusstsein für Zugänge entwickeln", "Abholsituationen übersichtlich gestalten"],
        variations: ["Torregeln mit Kindern besprechen", "Übergabesituationen im Team reflektieren"],
        tips: ["Tor nie unbeaufsichtigt offen stehen lassen.", "Öffner und Schließmechanismus täglich kurz prüfen."],
        safety: ["Türöffner für Kinder unerreichbar montieren", "Quetschstellen vermeiden", "Tor muss nach dem Durchgang zuverlässig schließen"],
        documentation: ["Funktionskontrollen dokumentieren", "Störungen unmittelbar an die zuständige Stelle melden"],
        sources: ["Aufsichtspflicht", "Sichere Gestaltung elementarer Bildungseinrichtungen"]
      },
      wasserspiel: {
        title: "Wasserspiel",
        images: ["assets/wasserspiel/wasserspielwand.webp", "assets/wasserspiel/rohrwand.jpg", "assets/wasserspiel/wasserrinnen-sand.jpg", "assets/wasserspiel/matschanlage.jpg", "assets/wasserspiel/rohrsystem.jpg"],
        description: "Verbundenes Rohr- und Rinnensystem mit Handpumpe, Wasserrädern und Gefällestrecken. Wasser kann gestaut, umgeleitet und bis in den Sandbereich geführt werden.",
        areas: ["Natur und Technik", "Bewegung und Gesundheit"],
        age: "3 bis 6 Jahre",
        material: "Handpumpen, verbundene Rohre und Rinnen, Wasserräder, Sammelbecken, Becher, Siebe und Naturmaterialien",
        prep: "mittel",
        duration: "15 bis 40 Minuten",
        season: "Frühling bis Herbst",
        group: "2 bis 6 Kinder",
        goals: ["Gefälle, Strömung und Wasserkraft beobachten", "Pumpen, Leiten und Stauen koordinieren", "Zusammenhänge zwischen Wasser und Sand erforschen"],
        variations: ["Rohrverbindungen verändern", "Wasserräder vergleichen", "Wasser stauen und freigeben", "Matschkanäle in der Sandkiste bauen"],
        tips: ["Handtücher und Wechselkleidung mitdenken.", "Fragen der Kinder sichtbar notieren."],
        safety: ["Ständige Aufsicht", "Rutschgefahr vermeiden", "Wasser regelmäßig wechseln"],
        documentation: ["Kinderzeichnungen zu Beobachtungen", "Forscherfotos mit kurzen Zitaten"],
        sources: ["Naturwissenschaftliche Grunderfahrungen", "Sinnesbildung"]
      },
      wasserhaus: {
        title: "Wasser-Spielhaus",
        images: ["assets/wasserspiel/matschanlage.jpg", "assets/wasserspiel/wasserrinnen-sand.jpg"],
        description: "Erhöhtes, fest abgestütztes Spielhaus mit Leiter und geschützter Plattform. Von oben können Kinder Wasser in das angeschlossene Rinnensystem einfüllen.",
        areas: ["Bewegung und Gesundheit", "Natur und Technik", "Emotionen und soziale Beziehungen"],
        age: "3 bis 6 Jahre",
        material: "Holzplattform, Leiter mit Handlauf, Geländer, Einfüllgefäße und Anschlussrinne",
        prep: "gering",
        duration: "15 bis 40 Minuten",
        season: "Frühling bis Herbst",
        group: "Tandemtätigkeit bis Kleingruppe",
        goals: ["Sicheres Steigen und Balancieren", "Wasserwege gemeinsam planen", "Absprachen beim Einfüllen treffen"],
        variations: ["Wasser mit verschieden großen Gefäßen dosieren", "Startsignale für gemeinsame Wasserläufe vereinbaren"],
        tips: ["Gefäße in unterschiedlichen Größen bereitstellen.", "Kinder die Wasserwege vor dem Einfüllen vermuten lassen."],
        safety: ["Plattform nur bei trockenem, rutschfestem Belag nutzen", "Leiter und Geländer regelmäßig auf festen Sitz prüfen"],
        documentation: ["Strategien beim Transportieren und Dosieren beobachten", "Kindererklärungen zum Wasserweg festhalten"],
        sources: ["Bewegungsbildung", "Kooperatives naturwissenschaftliches Lernen"]
      },
      sandkasten: {
        title: "Sandkasten",
        images: ["assets/wasserspiel/wasserrinnen-sand.jpg", "assets/wasserspiel/matschanlage.jpg"],
        description: "Großzügige, eingefasste Sandspielfläche als Endpunkt des Wassersystems. Hier entstehen Kanäle, Becken, Bauwerke und unterschiedliche Matschkonsistenzen.",
        areas: ["Natur und Technik", "Ästhetik und Gestaltung", "Emotionen und soziale Beziehungen"],
        age: "2 bis 6 Jahre",
        material: "Sand, Schaufeln, Rechen, Eimer, Siebe, Trichter, Gießkannen, Rohre und Naturmaterialien",
        prep: "gering",
        duration: "20 bis 60 Minuten",
        season: "Frühling bis Herbst",
        group: "Einzelbeschäftigung bis Teilgruppe",
        goals: ["Materialeigenschaften von trockenem und nassem Sand vergleichen", "Räumlich planen und konstruieren", "Werkzeuge teilen und Vorhaben abstimmen"],
        variations: ["Kanallandschaft", "Staudamm-Baustelle", "Sandküche", "Spurensuche mit Naturmaterialien"],
        tips: ["Sandwerkzeug übersichtlich und erreichbar ordnen.", "Bauwerke über mehrere Tage bestehen lassen, wenn möglich."],
        safety: ["Sand regelmäßig reinigen und abdecken", "Wasseransammlungen nach der Nutzung entleeren"],
        documentation: ["Bauprozesse in Bildfolgen dokumentieren", "Hypothesen zu Stabilität und Wasserfluss notieren"],
        sources: ["Elementare Technikbildung", "Gestaltendes Lernen mit Naturmaterialien"]
      },
      bobbycar: {
        title: "Bobby-Cars und Fahrbereich",
        description: "Bewegungsangebot für Koordination, Verkehrsregeln, Rücksichtnahme und Rollenspiel.",
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen", "Ethik und Gesellschaft"],
        age: "2 bis 5 Jahre",
        material: "Bobby-Cars, Pylonen, Kreide, einfache Verkehrsschilder",
        prep: "gering",
        duration: "15 bis 45 Minuten",
        season: "ganzjährig bei geeignetem Wetter",
        group: "2 bis 8 Kinder",
        goals: ["Lenken, Bremsen und Ausweichen üben", "Regeln aushandeln", "Rücksichtnahme erleben"],
        variations: ["Tankstelle", "Waschanlage", "Führerschein-Parcours", "Lieferdienst-Spiel"],
        tips: ["Fahrwege markieren.", "Regeln gemeinsam mit Kindern entwickeln."],
        safety: ["Helm optional nach Hausstandard", "Kollisionen durch klare Wege reduzieren"],
        documentation: ["Regelplakat mit Kinderzeichnungen", "Beobachtung von Koordination und Sozialverhalten"],
        sources: ["Verkehrserziehung im Elementarbereich", "Bewegungsentwicklung"]
      },
      bobbyrennstrecke: {
        title: "Bobby-Car-Rennstrecke",
        description: "Etwa zwei Bobby-Cars breite Rundstrecke um das gesamte Gebäude mit Kurven, S-Kurven, Mittelmarkierungen, gesichertem Wegübergang und angeschlossenem Parkplatz.",
        areas: ["Bewegung und Gesundheit", "Ethik und Gesellschaft", "Emotionen und soziale Beziehungen"],
        age: "2 bis 6 Jahre",
        material: "Rundstrecke, Bobby-Cars, Parkplatzmarkierungen, Pylonen und einfache Verkehrsschilder",
        prep: "gering",
        duration: "15 bis 60 Minuten",
        season: "ganzjährig bei geeigneter Witterung",
        group: "Tandemtätigkeit bis Teilgruppe",
        goals: ["Lenken, Bremsen und Kurvenfahren koordinieren", "Abstände und Vorfahrt einschätzen", "Rücksichtnahme und Verkehrsregeln aushandeln"],
        variations: ["Führerschein-Parcours", "Lieferdienst", "Boxenstopp", "Parkplatzsuche", "Langsamfahr-Challenge"],
        tips: ["Fahrtrichtung gemeinsam festlegen.", "Fußwegquerungen deutlich markieren und besprechen."],
        safety: ["Strecke frei von Hindernissen halten", "Geschwindigkeit an Engstellen reduzieren", "Ein- und Ausfahrt des Parkplatzes übersichtlich halten"],
        documentation: ["Regelverständnis und Rücksichtnahme beobachten", "Streckenpläne von Kindern zeichnen lassen"],
        sources: ["Bewegungsentwicklung", "Verkehrserziehung im Elementarbereich"]
      },
      balancierstaemme: {
        title: "Balancierstämme",
        description: "Niedrige Holzstämme in unterschiedlichen Richtungen und Abständen laden zum Balancieren, Überschreiten und Erfinden eigener Bewegungswege ein.",
        areas: ["Bewegung und Gesundheit", "Natur und Technik"],
        age: "2 bis 6 Jahre",
        material: "Fest verankerte, abgerundete Holzstämme und Fallschutzfläche",
        prep: "gering",
        duration: "5 bis 30 Minuten",
        season: "ganzjährig bei trockenem Untergrund",
        group: "Einzelbeschäftigung bis Kleingruppe",
        goals: ["Gleichgewicht und Körperspannung entwickeln", "Schrittlängen anpassen", "Eigene Grenzen wahrnehmen"],
        variations: ["Seitwärts balancieren", "Naturmaterial transportieren", "Partnerweg", "Stopp-Signale"],
        tips: ["Verschiedene Lösungswege zulassen.", "Unterstützung nur so viel wie notwendig anbieten."],
        safety: ["Stämme auf festen Sitz und Splitter prüfen", "Nur bei rutschfestem Untergrund nutzen"],
        documentation: ["Individuelle Bewegungsstrategien beobachten", "Fortschritte in Bildfolgen festhalten"],
        sources: ["Psychomotorik", "Risikokompetenz im Kindesalter"]
      },
      tunnelhuegel: {
        title: "Tunnelhügel",
        description: "Kleine begrünte Hügel mit begehbaren Tunneln schaffen Rückzug, Versteckmöglichkeiten, Laufwege und Räume für fantasievolles Rollenspiel.",
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen", "Sprache und Kommunikation"],
        age: "2 bis 6 Jahre",
        material: "Begrünter Hügel, kurzer übersichtlicher Tunnel und rutschfester Durchgang",
        prep: "gering",
        duration: "10 bis 45 Minuten",
        season: "ganzjährig",
        group: "Einzelbeschäftigung bis Kleingruppe",
        goals: ["Kriechen, Laufen und Raumorientierung verbinden", "Nähe und Rückzug selbst regulieren", "Rollenspielorte gestalten"],
        variations: ["Geheimgang", "Tierhöhle", "Posttunnel", "Lauf- und Suchspiel"],
        tips: ["Lose Materialien für wechselnde Rollenspiele anbieten.", "Ein- und Ausgang frei und einsehbar halten."],
        safety: ["Tunnel regelmäßig kontrollieren", "Keine Gegenstände im Durchgang lagern", "Hügelhöhe altersangemessen halten"],
        documentation: ["Spielthemen und Raumaneignung beobachten", "Kinderideen zum Hügel sammeln"],
        sources: ["Raumpädagogik", "Psychomotorik"]
      },
      kletterwand: {
        title: "Niedrige Kletterwand",
        description: "Kleine geneigte Kletterwand mit gut erreichbaren Griffen und niedriger Fallhöhe für Kraft, Koordination und selbstständige Risikoeinschätzung.",
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen"],
        age: "3 bis 6 Jahre",
        material: "Geneigte Holzwand, verschiedenfarbige Griffe und Fallschutzmatte",
        prep: "gering",
        duration: "5 bis 25 Minuten",
        season: "Frühling bis Herbst",
        group: "Einzelbeschäftigung bis Kleingruppe",
        goals: ["Greifen, Stützen und Steigen koordinieren", "Kraft dosieren", "Mut und Risikokompetenz entwickeln"],
        variations: ["Farbrouten", "Nur bestimmte Griffe", "Partnerhinweise", "Klettergeschichte"],
        tips: ["Kinder selbstständig Routen wählen lassen.", "Nicht ungefragt hochheben oder sichern."],
        safety: ["Fallschutz und Griffe täglich sichtprüfen", "Absprungbereich frei halten", "Nur ein Kind je Route"],
        documentation: ["Routenwahl und Problemlösestrategien beobachten", "Selbsteinschätzungen der Kinder festhalten"],
        sources: ["Risikokompetenz", "Elementare Bewegungspädagogik"]
      },
      schwungtuch: {
        title: "Regenbogen-Schwungtuch",
        description: "Ausgebreitetes Schwungtuch in Regenbogenfarben für kooperative Bewegungs-, Wahrnehmungs- und Gruppenspiele.",
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen", "Ästhetik und Gestaltung"],
        age: "2 bis 6 Jahre",
        material: "Großes Regenbogen-Schwungtuch, leichte Bälle und gegebenenfalls Musik",
        prep: "gering",
        duration: "10 bis 30 Minuten",
        season: "Frühling bis Herbst",
        group: "Kleingruppe bis Gesamtgruppe",
        goals: ["Gemeinsame Bewegungen abstimmen", "Kraft und Rhythmus dosieren", "Gruppenzugehörigkeit erleben"],
        variations: ["Wellen", "Farbenwechsel", "Balltransport", "Pilz", "Platztausch"],
        tips: ["Mit ruhigen Bewegungen beginnen.", "Klare Start- und Stoppsignale vereinbaren."],
        safety: ["Ausreichend Abstand zu festen Geräten halten", "Kinder nicht unbeaufsichtigt unter dem Tuch lassen"],
        documentation: ["Kooperation und Impulskontrolle beobachten", "Bevorzugte Spielvarianten sammeln"],
        sources: ["Kooperative Bewegungsspiele", "Psychomotorik"]
      },
      spielhaus: {
        title: "Spielhaus",
        description: "Außen-Rollenspielort für Fantasie, Kommunikation und soziale Aushandlung.",
        areas: ["Emotionen und soziale Beziehungen", "Sprache und Kommunikation"],
        age: "3 bis 6 Jahre",
        material: "Spielhaus, Tücher, lose Naturmaterialien, kleine Möbel",
        prep: "gering",
        duration: "20 bis 60 Minuten",
        season: "Frühling bis Herbst",
        group: "2 bis 5 Kinder",
        goals: ["Rollenspiel vertiefen", "Konflikte sprachlich lösen", "Eigene Spielideen entwickeln"],
        variations: ["Waldcafe", "Tierarztpraxis", "Poststation", "Familienhaus"],
        tips: ["Nicht zu voll ausstatten, damit Fantasie Raum behält.", "Rollenkonflikte als Lerngelegenheiten begleiten."],
        safety: ["Regelmäßig auf Splitter und stabile Teile prüfen", "Eingang frei halten"],
        documentation: ["Spielthemen und Rollenverteilungen beobachten", "Kinderinterviews zum Spielhaus"],
        sources: ["Rollenspielpädagogik", "Sozial-emotionales Lernen"]
      },
      rutsche: {
        title: "Rutsche",
        description: "Bewegungsgerät für Mut, Gleichgewicht, Körperkontrolle und soziale Regeln.",
        areas: ["Bewegung und Gesundheit", "Emotionen und soziale Beziehungen"],
        age: "2 bis 6 Jahre",
        material: "Rutsche, Fallschutz, Markierung für Wartebereich",
        prep: "gering",
        duration: "frei im Garten",
        season: "ganzjährig nach Wetter",
        group: "Einzelkind bis Kleingruppe",
        goals: ["Körperkontrolle entwickeln", "Warten und Abwechseln üben", "Risiko kompetent einschätzen"],
        variations: ["Rutschregeln mit Kindern formulieren", "Bewegungsgeschichte: Berg und Tal"],
        tips: ["Riskantes Spiel nicht unnötig verhindern, sondern sicher rahmen.", "Wartezonen sichtbar machen."],
        safety: ["Fallschutz prüfen", "Nur rutschen, wenn Auslauf frei ist"],
        documentation: ["Mutproben und Fortschritte beobachten", "Regelverständnis reflektieren"],
        sources: ["Risikokompetenz im Kindesalter", "Bewegungssicherheit"]
      },
      baum: {
        title: "Bäume und Naturinseln",
        description: "Natürliche Elemente für Schatten, Beobachtung, Jahreszeitenlernen und ökologische Bildung.",
        areas: ["Natur und Technik", "Ethik und Gesellschaft"],
        age: "2 bis 6 Jahre",
        material: "Bäume, Blätter, Rinde, Becherlupen, Sammelkörbe",
        prep: "gering",
        duration: "5 bis 45 Minuten",
        season: "ganzjährig",
        group: "Einzelkind bis Kleingruppe",
        goals: ["Jahreszeiten wahrnehmen", "Achtsamen Umgang mit Natur entwickeln", "Beobachten und Vergleichen üben"],
        variations: ["Baumtagebuch", "Blätter sortieren", "Rindenabdruck", "Schatten messen"],
        tips: ["Ein Baum kann zum langfristigen Projektpartner werden.", "Kinderfragen ernst nehmen und weiterverfolgen."],
        safety: ["Giftpflanzen und lose Äste prüfen", "Kletterregeln festlegen"],
        documentation: ["Jahreszeitenfotos", "Naturfund-Ausstellung"],
        sources: ["Naturpädagogik", "Bildung für nachhaltige Entwicklung"]
      }
    };

const socialFormLabels = {
      "Einzelkind, Kleingruppe, Eltern-Kind-Situation": "Einzelbeschäftigung, Kleingruppe oder Tandemtätigkeit mit einer elementarpädagogischen Fachperson",
      "Kleingruppe bis Gesamtgruppe": "Kleingruppe, Teilgruppe oder Gesamtgruppe",
      "2 bis 8 Kinder": "Tandemtätigkeit, Kleingruppe oder Teilgruppe",
      "Einzelkind bis Kleingruppe": "Einzelbeschäftigung, Tandemtätigkeit oder Kleingruppe",
      "2 bis 6 Kinder": "Tandemtätigkeit oder Kleingruppe",
      "1 bis 3 Kinder": "Einzelbeschäftigung, Tandemtätigkeit oder Kleingruppe",
      "1 bis 6 Kinder": "Einzelbeschäftigung, Tandemtätigkeit oder Kleingruppe",
      "Kleingruppe bis Halbgruppe": "Kleingruppe oder Teilgruppe",
      "Einzelkind bis Halbgruppe": "Einzelbeschäftigung, Tandemtätigkeit, Kleingruppe oder Teilgruppe",
      "2 bis 5 Kinder": "Tandemtätigkeit oder Kleingruppe"
    };
    Object.values(objectInfo).forEach(info => {
      info.group = socialFormLabels[info.group] || info.group;
    });

objectInfo.teamraum = {
  title: "Team- und Arbeitsraum",
  images: ["assets/references/holzgang-fenster.jpg", "assets/references/gruppenraum.jpg"],
  description: "Großer gemeinsamer Arbeitsraum mit zentralem Teamtisch, mehreren Laptops, kleiner Garderobe und verschließbaren Spinten.",
  areas: ["Ethik und Gesellschaft", "Sprache und Kommunikation", "Emotionen und soziale Beziehungen"],
  age: "Elementarpädagogische Fachpersonen und Auszubildende",
  material: "Großer Arbeitstisch, sechs Laptops, Sessel, Garderobenhaken und verschließbare Spinte",
  prep: "gering",
  duration: "nach Arbeitsvorhaben",
  season: "ganzjährig",
  group: "Tandemtätigkeit, Kleingruppe oder Teilgruppe",
  goals: ["Pädagogische Vorhaben gemeinsam planen", "Digitale Materialien kooperativ bearbeiten", "Teamkommunikation und Reflexion stärken"],
  variations: ["Planungssitzung", "Gemeinsame Dokumentation", "Kleingruppenarbeit an Laptops"],
  tips: ["Arbeitsplätze so anordnen, dass Blickkontakt und gemeinsame Bildschirmarbeit möglich bleiben.", "Persönliche Unterlagen in den Spinten sicher verwahren."],
  safety: ["Kabel stolpersicher führen", "Spinte kippsicher befestigen", "Bildschirmarbeitsplätze ergonomisch einrichten"],
  documentation: ["Planungsprotokolle", "Gemeinsam bearbeitete Bildungsdokumentationen"],
  sources: ["Team- und Qualitätsentwicklung in elementaren Bildungseinrichtungen"]
};

objectInfo.buero = {
  title: "Kleines Büro",
  images: ["assets/references/holzgang-fenster.jpg"],
  description: "Ruhiger, kompakter Arbeitsraum hinter dem Teamraum mit kleinem Schreibtisch, PC und Sitzplätzen.",
  areas: ["Ethik und Gesellschaft", "Sprache und Kommunikation"],
  age: "Elementarpädagogische Fachpersonen",
  material: "Kleiner Schreibtisch, PC, Tastatur und Sessel",
  prep: "gering",
  duration: "nach Arbeitsvorhaben",
  season: "ganzjährig",
  group: "Einzelbeschäftigung oder Tandemtätigkeit",
  goals: ["Konzentrierte Vor- und Nachbereitung ermöglichen", "Vertrauliche organisatorische Aufgaben bearbeiten", "Ruhige Gespräche führen"],
  variations: ["Einzelarbeit", "Kurzes Fachgespräch", "Digitale Dokumentation"],
  tips: ["Arbeitsfläche bewusst übersichtlich halten.", "Für vertrauliche Gespräche eine ruhige Atmosphäre sichern."],
  safety: ["Kabel stolpersicher führen", "Bildschirm ergonomisch positionieren"],
  documentation: ["Arbeitsnotizen", "Organisatorische Unterlagen"],
  sources: ["Professionelle Organisation elementarpädagogischer Arbeit"]
};

objectInfo.wasserwanne = {
  title: "Wasserwanne",
  description: "Flache Forschungswanne für Schwimmen und Sinken, Verdrängung, Strömung, Lösen und Mischen.",
  areas: ["Natur und Technik", "Sprache und Kommunikation"],
  age: "3 bis 6 Jahre", material: "Wasserwanne, Becher, Pipetten, Trichter, schwimmende und sinkende Gegenstände", prep: "mittel", duration: "15 bis 35 Minuten", season: "ganzjährig", group: "Tandemtätigkeit oder Kleingruppe",
  goals: ["Eigenschaften von Wasser beobachten", "Vermutungen zu Schwimmen und Sinken prüfen", "Beobachtungen dokumentieren"],
  variations: ["Schwimmen und Sinken", "Wassertransport", "Farben lösen", "Strömungsversuche"],
  tips: ["Zuerst frei erkunden lassen.", "Wie-Fragen zur Beschreibung von Veränderungen einsetzen."],
  safety: ["Verschüttetes Wasser sofort aufnehmen", "Nur ungiftige Materialien verwenden"], documentation: ["Forscherzeichnungen", "Fotofolgen mit Kinderzitaten"], sources: ["Forschungskreis", "Frühe naturwissenschaftliche Bildung"]
};

objectInfo.sandwanne = {
  title: "Sandwanne",
  description: "Trockene Materialwanne zum Sieben, Schütten, Wiegen, Spurenlegen und Untersuchen von Erde, Sand und Samen.",
  areas: ["Natur und Technik", "Ästhetik und Gestaltung"],
  age: "2 bis 6 Jahre", material: "Sandwanne, Sand, Erde, Samen, Siebe, kleine Schaufeln, Gefäße und Waage", prep: "gering", duration: "15 bis 40 Minuten", season: "ganzjährig", group: "Einzelbeschäftigung bis Kleingruppe",
  goals: ["Materialeigenschaften vergleichen", "Mengen und Gewichte untersuchen", "Spuren und Ordnungen gestalten"],
  variations: ["Korngrößen sieben", "Samen sortieren", "Volumen vergleichen", "Spurenlabor"],
  tips: ["Materialien in klar beschrifteten Gefäßen anbieten.", "Ordnungs- und Sortierideen der Kinder aufgreifen."],
  safety: ["Staubarme Materialien verwenden", "Hände nach Erdkontakt reinigen"], documentation: ["Sortierkriterien fotografieren", "Kinderhypothesen notieren"], sources: ["Elementare Mathematik- und Naturbildung"]
};

objectInfo.mikroskop = {
  title: "Mikroskopierstation",
  description: "Zwei Mikroskope am eigenen Forschertisch neben den großen Fenstern ermöglichen gemeinsames genaues Beobachten.",
  areas: ["Natur und Technik", "Sprache und Kommunikation"],
  age: "4 bis 6 Jahre", material: "Zwei Mikroskope, Objektträger, Pipetten, Pinzetten, Lupen und Naturmaterialien", prep: "mittel", duration: "10 bis 30 Minuten", season: "ganzjährig", group: "Tandemtätigkeit oder Kleingruppe",
  goals: ["Details vergrößert wahrnehmen", "Beobachtungen vergleichen und beschreiben", "Forschungsgeräte sorgfältig bedienen"],
  variations: ["Blätter und Samen", "Textilfasern", "Sandkörner", "Wassertropfen"],
  tips: ["Mit sichtbaren, kontrastreichen Objekten beginnen.", "Kinder einander ihre Entdeckungen zeigen lassen."],
  safety: ["Glasteile nur begleitet verwenden", "Mikroskope standsicher aufstellen"], documentation: ["Beobachtungszeichnungen", "Vergleich mit bloßem Auge und Lupe"], sources: ["Forschendes Lernen", "Visuelle Wahrnehmung"]
};

objectInfo.forscherkittel = {
  title: "Forscherkittel",
  description: "Frei erreichbare Forscherkittel am Kleiderständer unterstützen Rollenübernahme, Materialschutz und vorbereitende Routinen.",
  areas: ["Emotionen und soziale Beziehungen", "Natur und Technik"],
  age: "3 bis 6 Jahre", material: "Waschbare Forscherkittel in mehreren Größen und Kleiderständer", prep: "gering", duration: "während der Forschungsaktivität", season: "ganzjährig", group: "Einzelbeschäftigung bis Kleingruppe",
  goals: ["Sich selbstständig auf Forschungsaktivitäten vorbereiten", "Verantwortung für Kleidung und Material übernehmen", "Eine forschende Rolle entwickeln"],
  variations: ["Namensschilder", "Forschungsdienst", "Materialverantwortung"], tips: ["Kittelgrößen sichtbar kennzeichnen.", "An- und Ausziehen als selbstständige Routine begleiten."], safety: ["Kittel müssen gut passen", "Bänder und Ärmel dürfen nicht in Geräte geraten"], documentation: ["Selbstständige Vorbereitungsroutinen beobachten"], sources: ["Selbstkompetenz", "Alltagsintegriertes Lernen"]
};

objectInfo.materialregal = {
  title: "Offenes Forschungsmaterial-Regal",
  description: "Übersichtlich gegliedertes, frei zugängliches Regal für selbstständige Materialwahl und Rückordnung.",
  areas: ["Natur und Technik", "Ethik und Gesellschaft"],
  age: "3 bis 6 Jahre", material: "Lupen, Lupenbecher, Pinzetten, Pipetten, Tabletts, Erde, Samen und kleine Schaufeln", prep: "laufende Ordnung", duration: "nach Forschungsinteresse", season: "ganzjährig", group: "Einzelbeschäftigung bis Kleingruppe",
  goals: ["Forschungsmaterial passend auswählen", "Werkzeuge sachgerecht verwenden", "Materialien selbstständig pflegen und zurückordnen"],
  variations: ["Material des Monats", "Forschungsauftrag", "Sortierstation", "Naturfund-Regal"], tips: ["Materialien mit Bild und Begriff beschriften.", "Nur eine überschaubare Auswahl gleichzeitig anbieten."], safety: ["Kleinteile altersgerecht einsetzen", "Regal kippsicher befestigen", "Pipetten und Pinzetten regelmäßig reinigen"], documentation: ["Materialwahl und Werkzeuggebrauch beobachten"], sources: ["Vorbereitete Lernumgebung", "MINT-Didaktik"]
};

objectInfo.lichttisch = {
  title: "Statisch leuchtender Lichttisch",
  description: "Rechteckiger Lichttisch mit konstantem, ruhigem Licht für Legematerialien, geometrische Formen und additive Farbmischung.",
  areas: ["Natur und Technik", "Ästhetik und Gestaltung"],
  age: "3 bis 6 Jahre", material: "Lichttisch, transparente Acrylkreise, Dreiecke, Vierecke und Sechsecke in Rot, Grün, Blau und Gelb", prep: "gering", duration: "10 bis 40 Minuten", season: "ganzjährig", group: "Einzelbeschäftigung bis Kleingruppe",
  goals: ["Geometrische Formen erkennen, ordnen und kombinieren", "Farbüberlagerungen und additive Farbmischung untersuchen", "Muster und symmetrische Anordnungen entwickeln"],
  variations: ["Formenmandala", "Farben überlagern", "Symmetrie ergänzen", "Legebilder dokumentieren"], tips: ["Formen zunächst frei erkunden lassen.", "Licht konstant halten und keine Blinkeffekte einsetzen."], safety: ["Blendfreies, nicht flackerndes Licht verwenden", "Acrylteile auf scharfe Kanten prüfen"], documentation: ["Legebilder fotografieren", "Kindererklärungen zu Farbmischungen festhalten"], sources: ["Frühe mathematische Bildung", "Optik und additive Farbmischung"]
};

export const competencyFramework = {
  definition: "Kompetenzen werden nach Reitlinger (2007) und Weinert (1999) als Netzwerk aus Kenntnissen, Fähigkeiten und Fertigkeiten, Strategien und Routinen sowie Motivation verstanden, das Menschen in unterschiedlichen Situationen handlungsfähig macht.",
  foundations: [
    "In der österreichischen Elementarpädagogik werden Kompetenzen ganzheitlich und in Verbindung mit den sechs Bildungsbereichen des bundesländerübergreifenden BildungsRahmenPlans verstanden. Kinder gestalten Bildungsprozesse aktiv mit; elementarpädagogische Fachpersonen beobachten, begleiten und schaffen anregende Lernumgebungen.",
    "Roth (1968) unterscheidet Selbstkompetenz beziehungsweise personale Kompetenz, Sozialkompetenz beziehungsweise sozial-kommunikative Kompetenz und Sachkompetenz.",
    "Gisbert (2004) erweitert diese Einteilung um die lernmethodische Kompetenz.",
    "Aus der Zone der nächsten Entwicklung nach Wygotsky wird zusätzlich die Metakompetenz abgeleitet: Kinder reflektieren ihr Lernen und erschließen mit angemessener Begleitung nächste Entwicklungsschritte."
  ],
  categories: [
    { key: "self", title: "Selbstkompetenz / personale Kompetenz", description: "Eigene Bedürfnisse, Interessen, Fähigkeiten, Gefühle und Handlungsmöglichkeiten wahrnehmen und verantwortlich einsetzen." },
    { key: "social", title: "Sozialkompetenz / sozial-kommunikative Kompetenz", description: "Mit anderen kommunizieren, kooperieren, Perspektiven berücksichtigen und gemeinsame Vorhaben gestalten." },
    { key: "subject", title: "Sachkompetenz", description: "Wissen, Fähigkeiten und Fertigkeiten in konkreten Bildungs- und Handlungssituationen nutzen und erweitern." },
    { key: "learningMethod", title: "Lernmethodische Kompetenz", description: "Lernwege planen, Strategien erproben, Informationen nutzen, Erfahrungen dokumentieren und Wissen übertragen." },
    { key: "meta", title: "Metakompetenz", description: "Das eigene Denken, Lernen und Handeln reflektieren und mit Unterstützung nächste Entwicklungsschritte erschließen." }
  ]
};

function defaultCompetencies(info) {
  const subjectGoals = info.goals?.length ? info.goals : [`Kenntnisse und Fertigkeiten im Lernbereich ${info.title} aufbauen und anwenden.`];
  return {
    self: [`Eigene Interessen, Fähigkeiten und Handlungsmöglichkeiten im Lernbereich ${info.title} wahrnehmen und selbstwirksam einsetzen.`],
    social: [`Ideen, Beobachtungen und Vorgehensweisen mit anderen austauschen, zuhören und gemeinsame Absprachen verantwortungsvoll umsetzen.`],
    subject: subjectGoals,
    learningMethod: [`Fragen entwickeln, passende Vorgehensweisen erproben, Erfahrungen dokumentieren und Erkenntnisse auf neue Situationen übertragen.`],
    meta: [`Das eigene Denken, Lernen und Handeln beschreiben, überprüfen und mit angemessener Begleitung nächste Lernschritte erkennen.`]
  };
}

Object.values(objectInfo).forEach(info => {
  info.competencies = { ...defaultCompetencies(info), ...(info.competencies || {}) };
});
